# Generated by Django 5.1.2 on 2025-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_age_limit_alter_profile_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.profile'),
        ),
    ]
